#!/usr/bin/env bash
# Set up HTTP response for two servers
served_by="add_header X-Served-By $(cat /etc/hostname);"
sudo sed -i "/index.htm;/ a $served_by" /etc/nginx/sites-enabled/default
sudo service nginx restart
