#!/usr/bin/env bash
# Set up HTTP response for two servers
apt-get -y install nginx
echo "Holberton School for the win!" > /usr/share/nginx/html/index.html
new_string="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sed -i "/# Only/ i $new_string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
replace="#error_page"
new_string="error_page"
sed -i "s/$replace/$new_string/" /etc/nginx/sites-available/default
served_by="add_header X-Served-By $(cat /etc/hostname);"
sudo sed -i "/index.htm;/ a $served_by" /etc/nginx/sites-enabled/default
sudo service nginx restart
