#!/usr/bin/env bash
# This script manages daemon "manage_my_process"
case $1 in
	start)
		./manage_my_process&
		pgrep -f manage_my_process > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		pkill -f manage_my_process
		;;
	restart)
		pkill -f manage_my_process -9
		rm /var/run/my_process.pid
		./manage_my_process&
		pgrep -f manage_my_process > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*) echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
