#!/usr/bin/env bash
# This script reads in /etc/passwd and displays the username, group id, and home directory path for the user
filename="/etc/passwd"
while IFS=':' read -r -a line
do
	# echo -n ${lines[*]}
	# need fields 1,4,6
	#cut -d":" -f 1,4,6 -s
	echo ${line[0]}":"${line[3]}":"${line[5]}
done < "$filename"
