#!/usr/bin/env bash
# Transfers a file from client to server
if [[ $# -ne 3 ]]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
scp -o StrictHostChecking="no" -i "$4" "$1" "$3@$2:~/"
