#!/usr/bin/env bash
# Configure /redirect_me to another page permanently
sed -i '/# Only/ i Location /redirect_me\n{\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}' /etc/nginx/sites-available/default
