#!/usr/bin/env bash
# Create a custom 404 page
apt-get -y install nginx
new_string="location /redirect_me {\nrewrite ^/(.*)$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n}\n"
sed -i "/# Only/ i $new_string" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
replace="#error_page"
new_string="error_page"
sed -i "s/$replace/$new_string/" /etc/nginx/sites-available/default
service nginx restart
