#!/usr/bin/env bash
# Create a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
replace="#error_page"
new_string="error_page"
sed -i "s/$replace/$new_string/" /etc/nginx/sites-available/default
service nginx restart
