#!/usr/bin/env bash
# Configure container to run `nginx` as user `nginx` listening on all active IPs on port `8080`
sed -i "/#user/user nginx;/" /etc/nginx/nginx.conf
sed -i "/80/8080/" /etc/nginx/sites-enabled/default
chown nginx:nginx /etc/nginx/nginx.conf
service apache2 stop
pkill apache2
su -c "nginx -c /etc/nginx/nginx.conf" -s /bin/sh nginx
